#pragma once

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <profiling.h>

// Max entity count based on the function at Xrd+0x9d8fa0
constexpr size_t MaxEntities = 75;
constexpr size_t XrdStringSize = 32;
constexpr size_t XrdSaveStateSize = 0x23C732;

struct EntitySaveData
{
    float simpleActorTime = 0.f;   
};

struct SaveData
{
    // Data generated by xrd's save/load state functions.
    char xrdData[XrdSaveStateSize];

    // Custom per-entity data added for managing simple actors recreation.
    EntitySaveData entityData[MaxEntities];
};

// Mimicing part of a struct used by some of xrd's save/load state functions in
// order to redirect them to our own locations for saving/loading. There is a 
// global pointer to the struct that will be used by these functions. We
// mainly care about save/load addresses that are offset past a particular
// anchor point in the struct that save/load functions interface with.
struct SaveStateTracker
{
    DWORD padding0;
    DWORD saveStateIndex = 0;
    DWORD padding1;
    DWORD padding2;

    // The part of the struct returned to save/load state functions.
    DWORD getTrackerAnchor;
    DWORD padding3;

    // +0x8 (Offset from anchor)
    DWORD saveAddress1 = 0;

    // +0xc
    DWORD saveMemCpyCount = 0;

    // +0x10
    DWORD loadMemCpyCount = 0;

    // +0x14
    DWORD loadAddress = 0;

    // +0x18
    DWORD saveAddress2 = 0;
};

enum class SaveStateSectionBase 
{
    Module,
    Engine
};

// Part of the save state data. Each section has a function for loading and saving, 
// each function's address is relative to the Xrd module. 
//
// Each section resides at the specific offset, either from the xrd module or the 
// currently used AswEngine object.
struct SaveStateSection
{
    DWORD saveFunctionOffset;
    DWORD loadFunctionOffset;

    SaveStateSectionBase base;
    DWORD offset;
};

void AttachSaveStateDetours();
void DetachSaveStateDetours();
void SaveState(SaveData& dest);
void LoadState(const SaveData& src);

DECLARE_PROFILING_CATEGORY(SaveState)
DECLARE_PROFILING_CATEGORY(LoadState)
